services:
  postgres:
    container_name: database
    image: postgres:latest
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: raw
      POSTGRES_HOST_NAME: postgres
    ports:
      - 5432:5432
    networks:
      - postgres

  etl:
    container_name: etl-python
    build: .
    volumes:
      - ./etl:/etl
    networks:
      - postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: raw
      POSTGRES_HOST_NAME: postgres
    depends_on:
      - postgres
    ports:
      - 8000:8000

networks:
  postgres:
    driver: bridge